version: '3.8'

services:
  library-service:
    container_name: container_library_service
    image: library-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file:
      - .env
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${URL_FOR_DOCKER}
    depends_on:
      - library-postgres
    volumes:
      - ./src:/app/src
    networks:
      - library-network

  postgres:
    image: postgres:latest 
    container_name: container_library_postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - library_postgres_data:/var/lib/postgresql/data
    networks:
      - library-network

networks:
  library-network:
    driver: bridge

volumes:
  library_postgres_data:
